FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore /src/QuickStart/c#/publisher/*.csproj
RUN dotnet publish /src/QuickStart/c#/publisher/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:2.1-alpine3.7
WORKDIR /app
COPY --from=build-env /src/QuickStart/c#/publisher/out/ .

CMD ["dotnet", "aegp.dll"]