ARG base_tag=2.1-nanoserver-1809

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore \src\QuickStart\c#\publisher\publisher.csproj
RUN dotnet publish \src\QuickStart\c#\publisher\publisher.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:${base_tag}
WORKDIR /app
COPY --from=build-env /src/QuickStart/c#/publisher/out/ .

CMD ["dotnet", "aegp.dll"]