ARG base_tag=3.0-nanoserver-1809

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore \src\IoTModules\c#\subscriber\Subscriber.csproj
RUN dotnet publish \src\IoTModules\c#\subscriber\Subscriber.csproj -c Release -o /src/IoTModules/c#/subscriber/out

FROM mcr.microsoft.com/dotnet/core/aspnet:${base_tag}
WORKDIR /app

EXPOSE 8080/tcp
EXPOSE 4430/tcp

COPY --from=build-env /src/IoTModules/c#/subscriber/out/ .

CMD ["dotnet", "aegs.dll"]