FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore \src\QuickStart\c#\subscriber\Subscriber.csproj
RUN dotnet publish \src\QuickStart\c#\subscriber\Subscriber.csproj -c Release -o out

FROM mcr.microsoft.com/azure-functions/dotnet:2.0-nanoserver-1809
WORKDIR /app

ENV AzureWebJobsScriptRoot=/app
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

EXPOSE 80/tcp

COPY --from=build-env /src/QuickStart/c#/subscriber/out/ .