ARG base_tag=2.0-iot-edge
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore /src/QuickStart/c#/subscriber/*.csproj
RUN dotnet publish /src/QuickStart/c#/subscriber/*.csproj -c Release -o out

FROM mcr.microsoft.com/azure-functions/dotnet:${base_tag}
WORKDIR /app

ENV AzureWebJobsScriptRoot=/app
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

EXPOSE 80/tcp

COPY --from=build-env /src/QuickStart/c#/subscriber/out/ .
